### ISSUE TITLE
Segfault on freeswitchrs::raw::ptr_to_str for new freeswitch events 

### ISSUE THREAD

**Issue by hdiogenes** [friends-of-freeswitch/mod_prometheus#3]
New channel creation causes FreeSWITCH segfault. Backtrace and log+events attached.

[gdb-backtrace.txt](https://github.com/moises-silva/mod_prometheus/files/475398/gdb-backtrace.txt)
[freeswitch-events.txt](https://github.com/moises-silva/mod_prometheus/files/475399/freeswitch-events.txt)

**Comment by moises-silva** [comment]
@hdiogenes I'm looking into this. When capturing backtraces with gdb, you can do:

```
(gdb) set pagination off
(gdb) set logging file /tmp/bt.log
(gdb) set logging on
Copying output to /tmp/bt.log.
(gdb) thread apply all bt
(gdb) set logging off
Done logging to /tmp/bt.log.
(gdb) quit
```

**Comment by hdiogenes** [comment]
Well, I found that making freeswitchrs call `event_get_header_idx` instead of `event_get_header_ptr` does the trick. Again, I don't know if this is the best approach, but it does not segfault now, and the counters are being incremented in the right way.

```
diff --git a/src/lib.rs b/src/lib.rs
index 1f323ea..f0f929e 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -83,8 +83,8 @@ impl Event {
     }
     pub fn header<'a>(&'a self, name: &str) -> Option<Cow<'a, str>> {
         unsafe {
-            let v = fsr::event_get_header_ptr(self.0, name.as_ptr() as *const c_char);
-            fsr::ptr_to_str((*v).value)
+            let v = fsr::event_get_header_idx(self.0, name.as_ptr() as *const c_char, -1);
+            fsr::ptr_to_str(v)
         }
     }
 }
```

**Comment by moises-silva** [comment]
@hdiogenes hum, thanks for looking into this. It's odd, the code you changed should be functionally equivalent.

The FreeSWITCH C API event_get_header_idx() internally calls event_get_header_ptr() and then if the provided index is -1 (as you provided here) returns hp->value, which is what the code you replaced does (`(*v).value`)

**Comment by moises-silva** [comment]
@hdiogenes oh shoot, yeah I think this could be a case where a requested header is not present in the event. Do you see any warnings on the screen once you fixed this?

**Comment by moises-silva** [comment]
@hdiogenes Your fix is good regardless. Current code will definitely crash when the header is not found in the event. The new code uses the idx API which returns a char\* and ptr_to_str() will safely convert that to None. This fix must be pushed in the freeswitchrs code however. Can you open a PR in freeswitchrs? https://gitlab.com/wiresight/freeswitchrs/

The repo is down (Gitlab cloud having issues), but in the meantime please commit your fix directly in the fork I did directly on master: https://github.com/moises-silva/freeswitchrs

I'll give you commit rights to both mod_prometheus and freeswitchrs on my github. Feel free to commit fixes/enhancements as you see fit :)

**Comment by hdiogenes** [comment]
Sure, there are two warnings:

```
[WARNING] mod_prometheus.rs:178 Received channel create event with no call direction: "<No Body>"
[WARNING] mod_prometheus.rs:220 Received channel hangup event with no call answer time information: "<No Body>"
```

Now I see that internally FS makes most of the calls through this macro, which indicates we're on the right path:
`#define switch_event_get_header(_e, _h) switch_event_get_header_idx(_e, _h, -1)`

Thank you for the commit permission! I've already pushed the new code there.

**Comment by moises-silva** [comment]
@hdiogenes You forgot to open an issue and PR directly on the freeswitchrs upstream repo, my github repo is just a mirror with fixes I've made but not yet integrated in upstream freeswitchrs, which is hosted in gitlab.com

I've updated a PR I had upstream with freeswitchrs and may be @MichaelGG can merge them soon.

https://gitlab.com/wiresight/freeswitchrs/merge_requests/2
